mode = "mpc"
key_file = "/Users/johnzampolin/go/src/github.com/jackzampolin/horcrux/data/signer1/priv-key-shard.json"
state_dir = "/Users/johnzampolin/go/src/github.com/jackzampolin/horcrux/data/signer1/"
chain_id = "test-chain-id"
cosigner_threshold = 2
cosigner_listen_address = "tcp://0.0.0.0:2222"

[[cosigner]]
id = 2
remote_address = "tcp://0.0.0.0:2223"

[[cosigner]]
id = 3
remote_address = "tcp://0.0.0.0:2224"

[[node]]
address = "tcp://0.0.0.0:1234" 

[[node]]
address = "tcp://0.0.0.0:1235" 
